export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const FETCH_INGREDIENT = 'FETCH_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED'


//order
export const PURCHASE_BURGER_REQUEST = 'PURCHASE_BURGER_REQUEST'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'

export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';


export const AUTH_START_SAGA = 'AUTH_START_SAGA';
export const AUTH_START = 'AUTH_STAR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT_SAGA = 'AUTH_LOGOUT_SAGA'
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_CHECK_TIMEOUT_SAGA = "AUTH_CHECK_TIMEOUT_SAGA"
export const AUTH_CHECK_STATE_SAGA = "AUTH_CHECK_STATE_SAGA"

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"
export const RESET_INGREDIENTS = "RESET_INGREDIENTS"


